import t

@t.seq("pat.fa", num=0)
def test_pat(rec):
    t.eq(rec.ident, {"gi": "412263", "emb": "CAA00865.1"})
    t.eq(rec.desc, "lambda N and streptolysin O antigen fusion protein " \
                    "[synthetic construct]")
    t.eq(rec.seq, ''.join("""
        MDAQTRRRERRAEKQAQWKAANPLLVGVSAKPVNQWHDNYSGGNTLPARTQYTESMVYSKSQ
        IEAALNVNSKILDGTLGIDFKSISKGEKKVMIAAYKQIFYTVSANLPNNPADVFDKSVTFKE
        LQRKGVSNEAPPLFVSNVAYGRTVFVKLETSSKSNDVEAAFSAALKGTDVKTNGKYSDILEN
        SSFTAVVLGGDAAEHNKVVTKDFDVIRNVIKDNATFSRKNPAYPISYTSVFLKNNKIAGVNN
        RTEYVETTSTEYTSGKINLSHQGAYVAQYEILWDEINYDDKGKEVITKRRWDNNWYSKTSPF
        STVIPLGANSRNIRIMARECTGLAWEWWRKVIDERDVKLSKEINVNISGSTLSPYGSITYK
    """.split()))